
import React, {useEffect, useRef, useState, useCallback} from 'react';
import {createRoot} from 'react-dom/client';
import {ArrowLeft, ArrowRight, BarChart3, Building2, Check, CheckCircle2, ChevronRight, ClipboardList, Clock3, Coffee, Croissant, CupSoda, IndianRupee, Leaf, Loader2, LockKeyhole, LogOut, MapPin, Minus, PackageCheck, Plus, PlusCircle, ReceiptText, Search, ShieldCheck, ShoppingBag, Sparkles, Trash2, UserRound, WalletCards, Wifi, WifiOff, X} from 'lucide-react';
import './styles.css';

const API = import.meta.env.VITE_API_URL || 'http://localhost:8000';
const WS = import.meta.env.VITE_WS_URL || 'ws://localhost:8000';
const money = p => new Intl.NumberFormat('en-IN',{style:'currency',currency:'INR',maximumFractionDigits:0}).format(p/100);
const number = n => String(n).padStart(3,'0');
const uid = () => crypto.randomUUID();
const read = (key, fallback) => {try{return JSON.parse(localStorage.getItem(key)) ?? fallback}catch{return fallback}};
function useSaved(key, initial){const [value,setValue]=useState(()=>read(key,initial));useEffect(()=>{localStorage.setItem(key,JSON.stringify(value))},[key,value]);return [value,setValue]}
async function api(path,{method='GET',body,token,signal}={}){
  let r;try{r=await fetch(API+path,{method,signal,headers:{'Content-Type':'application/json',...(token?{Authorization:'Bearer '+token}:{})},body:body?JSON.stringify(body):undefined})}
  catch(e){if(e.name==='AbortError')throw e;throw new Error('Cannot reach the café. Check your connection and try again.')}
  const d=await r.json().catch(()=>({}));if(!r.ok){const e=new Error(typeof d.detail==='string'?d.detail:Array.isArray(d.detail)?d.detail.map(x=>x.msg).join('. '):'Something went wrong. Please try again.');e.status=r.status;throw e}return d;
}
function useLive(audience,token,onRefresh){
 const callback=useRef(onRefresh);callback.current=onRefresh;const [live,setLive]=useState(false);
 useEffect(()=>{if(!audience)return;let ws,retry,ping,closed=false;const refresh=()=>callback.current();const connect=()=>{if(closed)return;ws=new WebSocket(WS+'/ws?'+new URLSearchParams({audience,token:token||''}));ws.onopen=()=>{setLive(true);ping=setInterval(()=>ws.readyState===1&&ws.send('ping'),25000)};ws.onmessage=refresh;ws.onerror=()=>ws.close();ws.onclose=()=>{setLive(false);clearInterval(ping);if(!closed)retry=setTimeout(connect,1500)}};connect();refresh();const poll=setInterval(refresh,5000);window.addEventListener('online',refresh);return()=>{closed=true;clearTimeout(retry);clearInterval(ping);clearInterval(poll);window.removeEventListener('online',refresh);ws?.close()}},[audience,token]);return live;
}
function Button({children,busy,...props}){return <button {...props} disabled={props.disabled||busy}>{busy?<Loader2 className="spin" size={18}/>:null}{children}</button>}
function Alert({children}){return children?<div className="alert" role="alert">{children}</div>:null}
function Modal({title,onClose,children,className=''}){
 const ref=useRef();useEffect(()=>{const el=ref.current;el.showModal();const prev=document.activeElement;document.body.style.overflow='hidden';return()=>{document.body.style.overflow='';prev?.focus?.()}},[]);
 return <dialog ref={ref} className={'modal '+className} aria-label={title} onCancel={e=>{e.preventDefault();onClose()}} onClick={e=>e.target===ref.current&&onClose()}><button className="icon close" aria-label="Close dialog" onClick={onClose}><X/></button>{children}</dialog>
}
function Quantity({value,onChange,name='item'}){return <div className="quantity"><button aria-label={'Decrease '+name} onClick={()=>onChange(value-1)}><Minus size={15}/></button><span>{value}</span><button aria-label={'Increase '+name} disabled={value>=20} onClick={()=>onChange(value+1)}><Plus size={15}/></button></div>}
function FoodImage({item,className=''}){const [failed,setFailed]=useState(false);return failed||!item.image?<div className={'image-fallback '+className}><Coffee size={40}/></div>:<img className={className} src={item.image} alt={item.name} loading="lazy" onError={()=>setFailed(true)}/>}
function Customise({item,line,onSave,onClose}){
 const [mods,setMods]=useState(line?.mods||Object.fromEntries(item.modifier_groups.filter(g=>g.required).map(g=>[g.id,g.options[0].id])));
 const [qty,setQty]=useState(line?.qty||1);
 const unit=item.price_paise+item.modifier_groups.reduce((sum,g)=>sum+(g.options.find(o=>o.id===mods[g.id])?.price_paise||0),0);
 return <Modal title={'Customise '+item.name} onClose={onClose} className="customise">
 <FoodImage item={item} className="custom-image"/><div className="custom-body"><span className="eyebrow">MAKE IT YOURS</span><h2>{item.name}</h2><p className="muted">{item.description}</p>
 {item.modifier_groups.map(g=><fieldset key={g.id}><legend>{g.name}<small>{g.required?'Choose one':'Optional'}</small></legend>{!g.required&&<label className={!mods[g.id]?'choice chosen':'choice'}><input type="radio" name={g.id} checked={!mods[g.id]} onChange={()=>setMods({...mods,[g.id]:''})}/><span>No extra</span><small>Included</small></label>}{g.options.map(o=><label key={o.id} className={mods[g.id]===o.id?'choice chosen':'choice'}><input type="radio" name={g.id} checked={mods[g.id]===o.id} onChange={()=>setMods({...mods,[g.id]:o.id})}/><span>{o.name}</span><small>{o.price_paise?'+'+money(o.price_paise):'Included'}</small></label>)}</fieldset>)}
 <div className="allergen"><Leaf size={15}/> Ask our barista about allergens before ordering.</div></div>
 <div className="modal-bottom"><Quantity value={qty} onChange={v=>setQty(Math.max(1,v))} name={item.name}/><button className="primary" onClick={()=>onSave({key:line?.key||uid(),item,mods:Object.fromEntries(Object.entries(mods).filter(([,v])=>v)),qty,unit})}>{line?'Save changes':'Add to bag'} <span>{money(unit*qty)}</span><Plus size={18}/></button></div></Modal>
}
function Cart({cart,setCart,onEdit,onCheckout,busy,name,setName,mode,error,close}){
 const total=cart.reduce((s,l)=>s+l.unit*l.qty,0);
 return <aside className="cart-panel"><div className="cart-heading"><ShoppingBag size={22}/><h2>Your bag</h2><span>{cart.reduce((s,l)=>s+l.qty,0)}</span>{close&&<button className="icon mobile-close" onClick={close} aria-label="Close bag"><X/></button>}</div>
 {!cart.length?<div className="empty-cart"><div><ShoppingBag size={39} strokeWidth={1.3}/></div><h3>A little empty in here.</h3><p>Find your coffee. Add a little<br/>something on the side.</p></div>:<><div className="pickup"><MapPin size={18}/><div><b>Pickup at the counter</b><small>Grounded · Bengaluru</small></div><CheckCircle2 size={17}/></div><div className="cart-items">{cart.map(l=><div className="cart-item" key={l.key}><div className="cart-item-top"><b>{l.item.name}</b><strong>{money(l.unit*l.qty)}</strong></div><p>{Object.entries(l.mods).map(([g,o])=>l.item.modifier_groups.find(x=>x.id===g)?.options.find(x=>x.id===o)?.name).filter(Boolean).join(' · ')||'Classic, just as it is'}</p><div className="cart-controls"><button className="text-button" onClick={()=>onEdit(l)}>Customise <ChevronRight size={13}/></button><Quantity value={l.qty} name={l.item.name} onChange={qty=>setCart(c=>qty<1?c.filter(x=>x.key!==l.key):c.map(x=>x.key===l.key?{...x,qty}:x))}/></div></div>)}</div><label className="name-field">Name for pickup <span>optional</span><input maxLength={80} placeholder="What should we call you?" value={name} onChange={e=>setName(e.target.value)}/></label><div className="bill"><div><span>Item total</span><span>{money(total)}</span></div><div><span>Pickup fee</span><span className="green">FREE</span></div><div className="bill-total"><b>To pay</b><b>{money(total)}</b></div></div><Alert>{error}</Alert><Button className="primary checkout" busy={busy} onClick={onCheckout}>Continue to payment <ArrowRight size={18}/></Button><p className="secure"><ShieldCheck size={14}/>{mode==='demo'?'Demo checkout · no real money':'Razorpay test checkout · no real money'}</p></>}
 <div className="cart-footer"><Coffee size={16}/><span>Made fresh. Made for you.</span></div></aside>
}
function Menu({cart,setCart,onCheckout,busy,name,setName,mode,error}){
 const [menu,setMenu]=useState([]),[loading,setLoading]=useState(true),[menuError,setMenuError]=useState(''),[search,setSearch]=useState(''),[category,setCategory]=useState('All'),[selected,setSelected]=useState(null),[bagOpen,setBagOpen]=useState(false);
 const load=()=>{setLoading(true);api('/api/menu').then(d=>{setMenu(d);setMenuError('')}).catch(e=>setMenuError(e.message)).finally(()=>setLoading(false))};useEffect(load,[]);
 const categories=['All',...new Set(menu.map(x=>x.category))];const displayed=menu.filter(x=>(category==='All'||x.category===category)&&[x.name,x.description].join(' ').toLowerCase().includes(search.toLowerCase()));
 const edit=l=>{const item=menu.find(i=>i.id===l.item.id);if(item)setSelected({item,line:l})};
 const save=line=>{setCart(c=>c.some(x=>x.key===line.key)?c.map(x=>x.key===line.key?line:x):[...c,line]);setSelected(null)};
 const count=cart.reduce((s,l)=>s+l.qty,0);
 return <main className="menu-layout"><div className="menu-content"><div className="breadcrumb">Bengaluru <ChevronRight size={12}/> Grounded Coffee <ChevronRight size={12}/> Menu</div>
 <section className="cafe-card"><div className="cafe-info"><div className="cafe-label"><span className="small-mark"><Coffee size={18}/></span> YOUR DAILY GOOD THING</div><h1>Good days start<br/>with <em>great coffee.</em></h1><p>Handcrafted coffee. Buttery bakes.<br/>Your next little obsession.</p><div className="cafe-meta"><span><Coffee size={15}/> Brewed to order</span><span><MapPin size={15}/> Counter pickup</span></div></div><div className="hero-photo"><img src="/images/latte.jpg" alt="Freshly poured coffee with latte art"/><div className="photo-caption"><span>THE DAILY RITUAL</span><b>Slow sips.<br/>Good moments.</b></div></div></section>
 <div className="perks"><span><Sparkles size={17}/> A little ritual, a lot of joy</span><span><ShieldCheck size={17}/> Pay securely</span><span><Wifi size={17}/> Live pickup updates</span></div>
 <div className="menu-toolbar"><div><span className="eyebrow">FIND YOUR FAVOURITE</span><h2>What are you craving?</h2></div><label className="search"><Search size={18}/><input aria-label="Search menu" placeholder="Search coffee, bakes & more" value={search} onChange={e=>setSearch(e.target.value)}/>{search&&<button aria-label="Clear search" onClick={()=>setSearch('')}><X size={15}/></button>}</label></div>
 <div className="categories" aria-label="Menu categories">{categories.map(c=>{const Icon=c==='Coffee'?Coffee:c==='Cold'?CupSoda:c==='Bakery'?Croissant:Sparkles;return <button className={category===c?'selected':''} key={c} onClick={()=>setCategory(c)} aria-pressed={category===c}><Icon size={18}/>{c==='All'?'All items':c==='Cold'?'Iced & refreshing':c==='Coffee'?'Hot coffee':c}<span>{c==='All'?menu.length:menu.filter(i=>i.category===c).length}</span></button>})}</div>
 <Alert>{menuError}</Alert>{menuError&&<button className="secondary" onClick={load}>Try again</button>}
 <div className="section-heading"><h3>{search?'Search results':category==='All'?'The whole good menu':category==='Cold'?'Keep it cool':category==='Coffee'?'Brewed for your mood':'A little something extra'}</h3><span>{displayed.length} items</span></div>
 <section className="products">{loading?Array.from({length:4},(_,i)=><div className="skeleton" key={i}/>):displayed.map(item=><article className="product" key={item.id}><button className="product-image-button" onClick={()=>setSelected({item})} aria-label={'Customise '+item.name}><FoodImage item={item}/><span className="product-category">{item.category==='Cold'?'OVER ICE':item.category==='Coffee'?'FRESHLY BREWED':'FROM THE OVEN'}</span></button><div className="product-copy"><h3>{item.name}</h3><p>{item.description}</p><div className="product-bottom"><strong>{money(item.price_paise)}</strong><button className="add-button" onClick={()=>setSelected({item})} aria-label={'Add '+item.name}>ADD <Plus size={16}/></button></div><small>{item.modifier_groups.length?'Make it your way':'A perfect coffee companion'}</small></div></article>)}</section>
 {!loading&&!displayed.length&&!menuError&&<div className="empty"><Search/><h3>No matches just yet.</h3><p>Try another search or explore all items.</p><button className="secondary" onClick={()=>{setSearch('');setCategory('All')}}>See the whole menu</button></div>}
 <footer className="menu-footer"><Coffee/><b>Life happens. Coffee helps.</b><span>GROUNDed COFFEE · BENGALURU</span><small>Photos are illustrative. Your cup is made fresh.</small></footer></div>
 <div className={'cart-container '+(bagOpen?'cart-open':'')}><Cart {...{cart,setCart,onCheckout,busy,name,setName,mode,error}} onEdit={edit} close={()=>setBagOpen(false)}/></div>
 {count>0&&<button className="mobile-bag" onClick={()=>setBagOpen(true)}><ShoppingBag size={18}/>{count} {count===1?'item':'items'} <b>View bag · {money(cart.reduce((s,l)=>s+l.unit*l.qty,0))}</b><ArrowRight size={18}/></button>}
 {selected&&<Customise {...selected} onSave={save} onClose={()=>setSelected(null)}/>}</main>
}
function DemoPayment({order,token,onClose,onDone}){
 const [busy,setBusy]=useState(false),[error,setError]=useState('');
 const pay=async outcome=>{setBusy(true);try{await api('/api/orders/'+order.id+'/demo-payment',{method:'POST',token,body:{outcome}});onDone()}catch(e){setError(e.message)}finally{setBusy(false)}};
 return <Modal title="Demo payment" onClose={()=>!busy&&onClose()} className="payment-modal"><div className="payment-icon"><ShieldCheck size={28}/></div><span className="eyebrow">LOCAL PAYMENT SIMULATOR</span><h2>Try the full experience.</h2><p>No cards. No real money.<br/>Simulate a payment for order #{number(order.number)}.</p><div className="payment-amount">{money(order.total_paise)}</div><Alert>{error}</Alert><Button busy={busy} className="primary" onClick={()=>pay('captured')}>Simulate successful payment <Check size={18}/></Button><Button className="secondary" disabled={busy} onClick={()=>pay('failed')}>Simulate failed payment</Button><small>Razorpay test checkout appears when test keys are configured.</small></Modal>
}
const statusCopy={awaiting_payment:['Your coffee is one step away.','Complete payment to send your order to our barista.'],paid:['You’re in good hands.','Your order is confirmed. We’ll start making it shortly.'],preparing:['A little craft. A lot of care.','Your barista is making your order fresh. Hang tight.'],ready:['Your good thing is ready.','Head to the pickup counter and show your order number.'],picked_up:['Enjoy every sip.','Thanks for spending a little part of your day with us.'],cancelled:['Your order is cancelled.','Any captured payment is automatically sent for a refund.']};
function Tracking({session,onBack,mode,onRefreshSession}){
 const [order,setOrder]=useState(session.order),[error,setError]=useState(''),[busy,setBusy]=useState(false),[demo,setDemo]=useState(false),[cancelOpen,setCancelOpen]=useState(false),[notice,setNotice]=useState('');
 const refresh=useCallback(async()=>{try{const d=await api('/api/orders/'+session.order.id,{token:session.token});setOrder(d);onRefreshSession?.(d);setError('')}catch(e){setError(e.message)}},[session.order.id,session.token]);
 const live=useLive(order.id,session.token,refresh);
 const pay=async()=>{setBusy(true);setError('');try{const p=await api('/api/orders/'+order.id+'/retry-payment',{method:'POST',token:session.token});if(p.mode==='demo')setDemo(true);else{if(!window.Razorpay)throw new Error('Checkout could not load. Check your connection and retry.');const rz=new window.Razorpay({key:p.key_id,amount:p.amount,currency:p.currency,order_id:p.provider_order_id,name:'Grounded Coffee',description:'Order #'+number(order.number),theme:{color:'#b94d32'},handler:()=>{setNotice('Payment submitted. Waiting for secure confirmation…');refresh()},modal:{ondismiss:()=>setNotice('Checkout closed. You can retry payment on this same order.')}});rz.on('payment.failed',()=>{setNotice('Payment did not complete. You can safely retry this order.');refresh()});rz.open()}}catch(e){setError(e.message)}finally{setBusy(false)}};
 const cancel=async()=>{setBusy(true);try{setOrder(await api('/api/orders/'+order.id+'/cancel',{method:'POST',token:session.token}));setCancelOpen(false)}catch(e){setError(e.message);setCancelOpen(false)}finally{setBusy(false)}};
 const [title,description]=statusCopy[order.status]||statusCopy.awaiting_payment;
 const stages=['paid','preparing','ready','picked_up'],active=stages.indexOf(order.status);
 return <main className="tracking-layout"><button className="back" onClick={onBack}><ArrowLeft size={18}/> Back to menu</button><section className="tracking-card"><div className={'tracking-status '+order.status}>{order.status==='ready'?<ShoppingBag size={36}/>:order.status==='cancelled'?<X size={36}/>:order.status==='picked_up'?<CheckCircle2 size={36}/>:<Coffee size={36}/>}</div><span className="eyebrow">YOUR DAILY GOOD THING</span><h1>{title}</h1><p>{description}</p><div className="order-number"><span>PICKUP NUMBER</span><b>#{number(order.number)}</b><small>{order.customer_name} · Grounded, Bengaluru</small></div><div className={'connection '+(live?'connected':'')} aria-live="polite">{live?<Wifi size={14}/>:<WifiOff size={14}/>} {live?'Live updates connected':'Reconnecting · checking every 5 seconds'}</div>
 {order.status!=='cancelled'&&<div className="progress-steps">{stages.map((s,i)=><div key={s} className={i<=active?'complete':''}><span>{i<=active?<Check size={16}/>:i+1}</span><b>{['Confirmed','Preparing','Ready','Picked up'][i]}</b></div>)}</div>}
 {order.payment_status==='failed'&&order.status==='awaiting_payment'&&<Alert>Payment failed. No new order is needed—retry below.</Alert>}<Alert>{error}</Alert>{notice&&order.status==='awaiting_payment'&&<p className="notice">{notice}</p>}
 {order.status==='awaiting_payment'&&<Button busy={busy} className="primary" onClick={pay}>{order.payment_status==='failed'?'Retry payment':'Pay for this order'} · {money(order.total_paise)} <ArrowRight size={18}/></Button>}
 {['paid','awaiting_payment'].includes(order.status)&&<button className="text-button cancel-link" onClick={()=>setCancelOpen(true)}>Cancel order</button>}
 {['preparing','ready'].includes(order.status)&&<p className="fine">Need to cancel? Please speak to the barista.</p>}
 {order.refunds?.map((r,i)=><div key={i} className="refund-info"><ShieldCheck size={18}/><span>{r.status==='processed'?'Refund processed':r.status==='failed'?'Refund needs attention — please contact the barista':'Refund in progress'} · {money(r.amount_paise)}{mode==='demo'?' (simulated)':''}</span></div>)}
 </section><section className="order-receipt"><h2>Your order</h2>{order.items.map((l,i)=><div key={i}><span><b>{l.quantity} × {l.name}</b><small>{l.modifiers.join(' · ')}</small></span><b>{money(l.unit_price_paise*l.quantity)}</b></div>)}<div className="receipt-total"><b>Total</b><b>{money(order.total_paise)}</b></div></section>
 {demo&&<DemoPayment {...{order,token:session.token}} onClose={()=>setDemo(false)} onDone={()=>{setDemo(false);refresh()}}/>}
 {cancelOpen&&<Modal title="Cancel your order" onClose={()=>setCancelOpen(false)} className="confirm-modal"><h2>Cancel this order?</h2><p>If your payment has been captured, we’ll request a full refund automatically.</p><Alert>{error}</Alert><Button className="primary" busy={busy} onClick={cancel}>Yes, cancel order</Button><button className="secondary" onClick={()=>setCancelOpen(false)}>Keep my coffee coming</button></Modal>}</main>
}
function StaffLogin({onLogin,mode,onBack}){
 const [pin,setPin]=useState(''),[error,setError]=useState(''),[busy,setBusy]=useState(false);
 const submit=async e=>{e.preventDefault();setBusy(true);try{onLogin((await api('/api/staff/session',{method:'POST',body:{pin}})).token)}catch(e){setError(e.message)}finally{setBusy(false)}};
 return <main className="login business-login"><form onSubmit={submit}>{onBack&&<button type="button" className="login-back" onClick={onBack}><ArrowLeft size={16}/> Back</button>}<div className="payment-icon"><LockKeyhole/></div><span className="eyebrow">GROUNDED BUSINESS</span><h1>Welcome back.</h1><p>Secure access to orders, payments and live café operations.</p><label>Business PIN<input type="password" inputMode="numeric" autoComplete="current-password" value={pin} onChange={e=>setPin(e.target.value)} required autoFocus placeholder="Enter your 4-digit PIN"/></label><Alert>{error}</Alert><Button className="primary" busy={busy}>Open operations <ArrowRight size={18}/></Button>{mode==='demo'&&<small>Local demo PIN: 2468</small>}<div className="login-trust"><ShieldCheck size={14}/> Encrypted staff session · expires in 12 hours</div></form></main>
}
function Welcome({savedName,onGuest,onBusiness,onServing}){
 const [name,setName]=useState(savedName||'');
 const submit=e=>{e.preventDefault();if(name.trim())onGuest(name.trim())};
 return <main className="access-page"><section className="access-story"><div className="access-logo"><span className="brand-mark"><Coffee size={25}/></span><b>grounded<span>.</span></b></div><div className="access-story-copy"><span className="eyebrow">COFFEE & EVERYDAY JOY</span><h1>Your daily good thing,<br/><em>made simple.</em></h1><p>Order beautifully. Follow every step. Pick up exactly when it’s ready.</p><div className="access-proof"><span><ShieldCheck/>Secure test payments</span><span><Wifi/>Live order tracking</span></div></div><div className="access-photo-credit">Grounded Coffee · Bengaluru</div></section><section className="access-panel"><div className="access-card"><span className="eyebrow">WELCOME TO GROUNDED</span><h2>How are you joining us?</h2><p>Start a guest order or open the business workspace.</p><form onSubmit={submit} className="guest-entry"><label>Your name<input autoFocus maxLength={80} value={name} onChange={e=>setName(e.target.value)} placeholder="What should we call you?"/></label><Button className="primary" disabled={!name.trim()}>Continue as guest <ArrowRight size={18}/></Button></form><div className="access-divider"><span>or</span></div><button className="business-entry" onClick={onBusiness}><span><Building2 size={21}/></span><div><b>Business workspace</b><small>Orders, payments and café operations</small></div><ChevronRight size={18}/></button><button className="display-link" onClick={onServing}>Open public “Now Serving” display <ArrowRight size={14}/></button><small className="access-fine">No customer account or password required.</small></div></section></main>
}
function CounterOrder({token,onClose,onCreated}){
 const [menu,setMenu]=useState([]),[cart,setCart]=useState({}),[name,setName]=useState(''),[busy,setBusy]=useState(false),[error,setError]=useState('');
 useEffect(()=>{api('/api/menu').then(setMenu).catch(e=>setError(e.message))},[]);
 const quantity=id=>cart[id]||0;
 const change=(id,delta)=>setCart(c=>({...c,[id]:Math.max(0,(c[id]||0)+delta)}));
 const selected=menu.filter(item=>quantity(item.id)>0);
 const defaults=item=>item.modifier_groups.filter(g=>g.required).map(g=>({group_id:g.id,option_id:g.options[0].id}));
 const unit=item=>item.price_paise+item.modifier_groups.filter(g=>g.required).reduce((sum,g)=>sum+(g.options[0]?.price_paise||0),0);
 const total=selected.reduce((sum,item)=>sum+unit(item)*quantity(item.id),0);
 const submit=async()=>{setBusy(true);setError('');try{const order=await api('/api/business/orders',{method:'POST',token,body:{request_key:uid(),customer_name:name||'Walk-in guest',items:selected.map(item=>({menu_item_id:item.id,quantity:quantity(item.id),modifiers:defaults(item)}))}});onCreated(order)}catch(e){setError(e.message)}finally{setBusy(false)}};
 return <Modal title="Create counter order" onClose={onClose} className="counter-modal"><div className="counter-modal-head"><span className="eyebrow">NEW COUNTER ORDER</span><h2>Add a walk-in order.</h2><p>Prices are calculated securely from the live menu. The order is recorded as paid at counter.</p></div><div className="counter-form"><label>Customer name <span>optional</span><input maxLength={80} value={name} onChange={e=>setName(e.target.value)} placeholder="Walk-in guest"/></label><div className="counter-menu">{menu.map(item=><div className="counter-menu-row" key={item.id}><FoodImage item={item}/><div><b>{item.name}</b><small>{money(unit(item))}{item.modifier_groups.some(g=>g.required)?' · house default':''}</small></div><Quantity name={item.name} value={quantity(item.id)} onChange={v=>setCart(c=>({...c,[item.id]:Math.max(0,v)}))}/></div>)}</div><Alert>{error}</Alert></div><div className="counter-checkout"><div><span>{selected.reduce((sum,item)=>sum+quantity(item.id),0)} items</span><b>{money(total)}</b></div><Button className="primary" disabled={!selected.length} busy={busy} onClick={submit}>Create paid order <ArrowRight size={17}/></Button></div></Modal>
}
const statusLabel={awaiting_payment:'Awaiting payment',paid:'Confirmed',preparing:'Preparing',ready:'Ready',picked_up:'Picked up',cancelled:'Cancelled'};
const paymentLabel={created:'Pending',failed:'Failed',captured:'Paid',refund_pending:'Refunding',refunded:'Refunded'};
function BusinessDashboard({mode,onExit,onServing}){
 const [token,setToken]=useSaved('grounded.staff',''),[data,setData]=useState(null),[error,setError]=useState(''),[busy,setBusy]=useState(''),[cancelling,setCancelling]=useState(null),[reason,setReason]=useState(''),[creating,setCreating]=useState(false),[tab,setTab]=useState('overview'),[search,setSearch]=useState(''),[filter,setFilter]=useState('all');
 const refresh=useCallback(async()=>{if(!token)return;try{setData(await api('/api/business/dashboard',{token}));setError('')}catch(e){if(e.status===401)setToken('');else setError(e.message)}},[token]);
 const live=useLive(token?'barista':null,token,refresh);
 const update=async(order,status)=>{setBusy(order.id);try{await api('/api/barista/orders/'+order.id,{method:'PATCH',token,body:{status,reason:status==='cancelled'?reason:null}});setCancelling(null);setReason('');await refresh()}catch(e){setError(e.message)}finally{setBusy('')}};
 if(!token)return <StaffLogin onLogin={setToken} mode={mode} onBack={onExit}/>;
 const metrics=data?.metrics||{},payments=data?.payments||{},orders=data?.orders||[];
 const active=orders.filter(o=>['paid','preparing','ready'].includes(o.status));
 const shown=orders.filter(o=>(filter==='all'||o.status===filter||o.payment_status===filter)&&('#'+number(o.number)+' '+o.customer_name+' '+o.items.map(i=>i.name).join(' ')).toLowerCase().includes(search.toLowerCase()));
 const next={paid:'preparing',preparing:'ready',ready:'picked_up'};
 const nextCopy={paid:'Start',preparing:'Ready',ready:'Picked up'};
 const table=<div className="orders-table-wrap"><table className="orders-table"><thead><tr><th>Order</th><th>Customer</th><th>Items</th><th>Payment</th><th>Fulfilment</th><th>Total</th><th></th></tr></thead><tbody>{shown.map(o=><tr key={o.id}><td><b>#{number(o.number)}</b><small>{new Date(o.created_at).toLocaleTimeString([],{hour:'2-digit',minute:'2-digit'})}</small></td><td>{o.customer_name}<small>{o.payment_method==='counter'?'Counter order':'Online order'}</small></td><td>{o.items.reduce((s,i)=>s+i.quantity,0)} items<small>{o.items.map(i=>i.name).join(', ')}</small></td><td><span className={'status-chip payment '+o.payment_status}>{paymentLabel[o.payment_status]||o.payment_status}</span></td><td><span className={'status-chip '+o.status}>{statusLabel[o.status]}</span></td><td><b>{money(o.total_paise)}</b></td><td><div className="row-actions">{next[o.status]&&<Button busy={busy===o.id} onClick={()=>update(o,next[o.status])}>{nextCopy[o.status]}</Button>}{['awaiting_payment','paid','preparing','ready'].includes(o.status)&&<button className="danger-icon" title="Cancel order" onClick={()=>{setCancelling(o);setReason('')}}><Trash2 size={16}/></button>}</div></td></tr>)}{!shown.length&&<tr><td colSpan="7"><div className="table-empty"><ReceiptText/><b>No matching orders</b><span>Try a different status or search.</span></div></td></tr>}</tbody></table></div>;
 return <div className="business-shell"><aside className="business-sidebar"><div className="os-brand"><span><Coffee/></span><div><b>Grounded</b><small>BUSINESS OS</small></div></div><nav><button className={tab==='overview'?'active':''} onClick={()=>setTab('overview')}><BarChart3/>Overview</button><button className={tab==='orders'?'active':''} onClick={()=>setTab('orders')}><ClipboardList/>Orders <span>{active.length}</span></button><button className={tab==='payments'?'active':''} onClick={()=>setTab('payments')}><WalletCards/>Payments</button></nav><div className="sidebar-bottom"><button onClick={onServing}><Wifi/>Now serving display</button><button onClick={()=>{setToken('');onExit()}}><LogOut/>Sign out</button><div className="business-profile"><span>GC</span><div><b>Café team</b><small>Grounded Bengaluru</small></div></div></div></aside><main className="business-main"><header className="business-header"><div><span className="eyebrow">GROUNDed · BENGALURU</span><h1>{tab==='overview'?'Good evening, team.':tab==='orders'?'Every order, in control.':'Payments at a glance.'}</h1><p>{tab==='overview'?'Here’s how the café is moving today.':tab==='orders'?'Manage the live queue and complete order history.':'Monitor payment health, refunds and net sales.'}</p></div><div><span className={'live-pill '+(live?'connected':'')}><span></span>{live?'Live sync':'Reconnecting'}</span><button className="primary new-order" onClick={()=>setCreating(true)}><PlusCircle size={18}/>New order</button></div></header><Alert>{error}</Alert>
 {tab==='overview'&&<><section className="metric-grid"><article><div className="metric-icon orders"><ReceiptText/></div><span>Orders today</span><strong>{metrics.orders_today||0}</strong><small>{metrics.active_orders||0} currently active</small></article><article><div className="metric-icon sales"><IndianRupee/></div><span>Net sales</span><strong>{money(metrics.net_sales_paise||0)}</strong><small>{money(metrics.gross_sales_paise||0)} gross</small></article><article><div className="metric-icon complete"><PackageCheck/></div><span>Completed</span><strong>{metrics.completed_orders||0}</strong><small>Picked up today</small></article><article><div className="metric-icon refunds"><WalletCards/></div><span>Refunded</span><strong>{money(metrics.refunds_paise||0)}</strong><small>{metrics.cancelled_orders||0} cancelled orders</small></article></section><section className="overview-grid"><div className="ops-card"><div className="card-heading"><div><span className="eyebrow">LIVE OPERATIONS</span><h2>Order flow</h2></div><button onClick={()=>setTab('orders')}>View all <ArrowRight size={14}/></button></div><div className="flow-list">{[['paid','Confirmed'],['preparing','Preparing'],['ready','Ready for pickup']].map(([state,label])=><div key={state}><span className={'flow-dot '+state}></span><div><b>{label}</b><small>{active.filter(o=>o.status===state).length?'Orders moving through the café':'No orders waiting'}</small></div><strong>{active.filter(o=>o.status===state).length}</strong></div>)}</div></div><div className="ops-card"><div className="card-heading"><div><span className="eyebrow">PAYMENT HEALTH</span><h2>Today’s payments</h2></div><span className="health-ok"><CheckCircle2/>Healthy</span></div><div className="payment-bars">{[['captured','Paid'],['created','Pending'],['failed','Failed'],['refunded','Refunded']].map(([state,label])=><div key={state}><span>{label}</span><div><i style={{width:Math.min(100,((payments[state]||0)/Math.max(1,metrics.orders_today||1))*100)+'%'}} className={state}></i></div><b>{payments[state]||0}</b></div>)}</div></div></section><section className="recent-card"><div className="card-heading"><div><span className="eyebrow">RECENT ACTIVITY</span><h2>Latest orders</h2></div><button onClick={()=>setTab('orders')}>Manage orders <ArrowRight size={14}/></button></div>{React.cloneElement(table,{})}</section></>}
 {tab!=='overview'&&<section className="orders-workspace"><div className="workspace-tools"><div className="search business-search"><Search/><input placeholder="Search order, customer or item" value={search} onChange={e=>setSearch(e.target.value)}/></div><select value={filter} onChange={e=>setFilter(e.target.value)}><option value="all">All statuses</option><option value="awaiting_payment">Awaiting payment</option><option value="paid">Confirmed</option><option value="preparing">Preparing</option><option value="ready">Ready</option><option value="picked_up">Picked up</option><option value="cancelled">Cancelled</option>{tab==='payments'&&<><option value="captured">Paid</option><option value="refunded">Refunded</option><option value="failed">Failed</option></>}</select><span>{shown.length} orders</span></div>{table}</section>}
 </main>{creating&&<CounterOrder token={token} onClose={()=>setCreating(false)} onCreated={()=>{setCreating(false);refresh()}}/>}{cancelling&&<Modal title="Cancel order" onClose={()=>setCancelling(null)} className="confirm-modal"><div className="danger-modal-icon"><Trash2/></div><h2>Remove order #{number(cancelling.number)}?</h2><p>This cancels the order but preserves its audit record. Any captured online payment is refunded automatically.</p><label>Reason for cancellation<textarea autoFocus maxLength={300} value={reason} onChange={e=>setReason(e.target.value)} placeholder="For example, customer requested cancellation"/></label><Alert>{error}</Alert><Button className="primary danger-button" disabled={!reason.trim()} busy={busy===cancelling.id} onClick={()=>update(cancelling,'cancelled')}>Cancel order safely</Button><button className="secondary" onClick={()=>setCancelling(null)}>Keep order</button></Modal>}</div>
}
function Serving(){
 const [orders,setOrders]=useState([]),[error,setError]=useState('');const refresh=async()=>{try{setOrders(await api('/api/serving'));setError('')}catch(e){setError(e.message)}};const live=useLive('public','',refresh);
 return <main className="serving"><div className="serving-heading"><span className="eyebrow">A LITTLE MOMENT OF ANTICIPATION</span><h1>Your next good thing.</h1><p>Watch for your number. We’ll take care of the rest.</p><span className={'connection '+(live?'connected':'')}><Wifi size={15}/>{live?'Updating live':'Reconnecting'}</span></div><Alert>{error}</Alert><div className="serving-columns"><section className="ready-board"><h2><ShoppingBag/> Ready for pickup</h2><p>Come on over. It’s all yours.</p><div>{orders.filter(o=>o.status==='ready').map(o=><b key={o.number}>#{number(o.number)}</b>)}</div>{!orders.some(o=>o.status==='ready')&&<span className="serving-empty">Your number will appear here.</span>}</section><section><h2><Coffee/> Being prepared</h2><p>Good coffee is worth a little patience.</p><div>{orders.filter(o=>['paid','preparing'].includes(o.status)).map(o=><b key={o.number}>#{number(o.number)}</b>)}</div>{!orders.some(o=>['paid','preparing'].includes(o.status))&&<span className="serving-empty">The bar is all caught up.</span>}</section></div></main>
}
function App(){
 const [view,setView]=useState(()=>location.hash.slice(1)||'login'),[cart,setCart]=useSaved('grounded.cart.v2',[]),[session,setSession]=useSaved('grounded.order.v2',null),[intent,setIntent]=useSaved('grounded.checkout.v2',null),[name,setName]=useSaved('grounded.name',''),[role,setRole]=useSaved('grounded.role',''),[mode,setMode]=useState(''),[busy,setBusy]=useState(false),[error,setError]=useState('');
 const navigate=v=>{location.hash=v;setView(v);window.scrollTo(0,0)};
 useEffect(()=>{const listener=()=>setView(location.hash.slice(1)||'login');window.addEventListener('hashchange',listener);api('/api/config').then(c=>setMode(c.payment_mode)).catch(()=>{});return()=>window.removeEventListener('hashchange',listener)},[]);
 const updateCart=fn=>{setCart(fn);setIntent(null);setError('')};
 const checkout=async()=>{setBusy(true);setError('');try{
   if(session&&['awaiting_payment','paid','preparing','ready'].includes(session.order.status)){navigate('track');return}
   const data=intent||{checkout_key:uid(),customer_name:name,items:cart.map(l=>({menu_item_id:l.item.id,quantity:l.qty,modifiers:Object.entries(l.mods).map(([group_id,option_id])=>({group_id,option_id}))}))};
   setIntent(data);localStorage.setItem('grounded.checkout.v2',JSON.stringify(data));
   const result=await api('/api/orders',{method:'POST',body:data});setSession(result);setCart([]);setIntent(null);navigate('track');
 }catch(e){setError(e.message)}finally{setBusy(false)}};
 const active=session&&['awaiting_payment','paid','preparing','ready'].includes(session.order.status);
 const guest=role==='guest'||Boolean(session);
 if(view==='login'||(!guest&&!['dashboard','barista','serving'].includes(view)))return <Welcome savedName={name} onGuest={guestName=>{setName(guestName);setRole('guest');navigate('menu')}} onBusiness={()=>navigate('dashboard')} onServing={()=>navigate('serving')}/>;
 if(view==='dashboard'||view==='barista')return <BusinessDashboard mode={mode} onExit={()=>navigate('login')} onServing={()=>navigate('serving')}/>;
 return <><div className="top-strip"><span>Small rituals. Better days.</span><span>{mode==='demo'?'DEMO EXPERIENCE · NO REAL PAYMENTS':'RAZORPAY TEST MODE · NO REAL PAYMENTS'}</span></div><header className="header"><a href="#menu" className="brand" onClick={()=>navigate(guest?'menu':'login')}><span className="brand-mark"><Coffee size={23}/></span><span>grounded<span className="brand-dot">.</span><small>COFFEE & EVERYDAY JOY</small></span></a><div className="location"><MapPin size={18}/><div><b>Bengaluru</b><small>Pickup at the counter</small></div></div><nav aria-label="Main navigation">{guest&&<a className={view==='menu'?'active':''} href="#menu">Menu</a>}<a className={view==='serving'?'active':''} href="#serving">Now serving</a><a href="#dashboard">Business</a></nav>{guest?<><button className="guest-pill" onClick={()=>{setRole('');navigate('login')}}><UserRound size={16}/><span>{name||'Guest'}</span><LogOut size={14}/></button><button className="header-order" onClick={()=>navigate(session?'track':'menu')}><ShoppingBag size={18}/><span>{active?'Your order':'Your bag'}</span><b>{active?'1':cart.reduce((s,l)=>s+l.qty,0)}</b></button></>:<button className="secondary header-login" onClick={()=>navigate('login')}>Sign in</button>}</header>
 {active&&view==='menu'&&<button className="active-order-banner" onClick={()=>navigate('track')}><span><Coffee size={17}/>Order #{number(session.order.number)} · {session.order.status.replaceAll('_',' ')}</span><b>Track order <ArrowRight size={16}/></b></button>}
 {view==='serving'?<Serving/>:view==='track'&&session?<Tracking session={session} mode={mode} onBack={()=>navigate('menu')} onRefreshSession={order=>setSession(s=>s&&s.order.id===order.id?{...s,order}:s)}/>:<Menu {...{cart,busy,name,setName,mode,error}} setCart={updateCart} onCheckout={checkout}/>}</>
}
createRoot(document.getElementById('root')).render(<App/>);
